### ISSUE TITLE
Is it possible to do server-side rendering on Heroku?

### ISSUE THREAD

**Issue by ethagnawl** [netguru/react_webpack_rails#124]
The Deployment doc doesn't mention this scenario explicitly and I've been unable to get this working on my own. My understanding is that Heroku only opens one port, so I'm fearful that this isn't possible, as the Rails application won't be able to communicate with the Node server via HTTP. 

In case it's helpful, here's the error I'm seeing: `2016-08-29T02:59:22.994608+00:00 app[web.1]: ActionView::Template::Error (Failed to open TCP connection to localhost:8081 (Connection refused - connect(2) for "localhost" port 8081))`

Assuming this is not possible, could anyone suggest an alternative approach? The one that jumps to mind is deploying node_server.js as its own application, but I'm hoping to not have to go down that rabbit hole.

**Comment by rpunkfu** [comment]
Hi Pete,

I will look into that this week, this is weird thought because as I
remember multiple processes on same Dyno can talk to themselves on any
ports..

**Comment by ethagnawl** [comment]
Did you ever get a chance to look into this issue, @rpunkfu?

I'm probably going to take another pass at my integration next week. If I can't get server-side rendering working on Heroku, I was thinking about forking the project (and submitting a PR, if you'd be open to it) and adding an option to specify a render server URI.

**Comment by rpunkfu** [comment]
Hi @ethagnawl, sorry but I didn't have enough time to investigate this issue, will do it asap :)

**Comment by ethagnawl** [comment]
@rpunkfu Thanks! :smile:

**Comment by jeffgran** [comment]
I just spent literally all day and half the night on figuring this out, and I'm happy to say that I did get it working, and it IS IN FACT POSSIBLE, even though heroku seems to be intentionally hiding that fact from their users (not that I'm bitter /s).

All the docs and all the stackoverflow answers say that it's not possible to run two http processes on the same dyno, but that's not true. I think it's partially a ploy to get you to use their enterprise product, or run more dynos than you need since they all cost money. 

OK seriously, I'll try to stop ranting and tell you how I got it to work. The only caveat is that only one process can respond to an *external* port, but that's ok because you only need one (the rails one) for this SSR setup. The node process can be on an internal firewalled localhost-only port, and in fact that's better for security purposes. We don't want the node process exposed to the real world.

Here's how: since you can only have one "web" process in your Procfile, what you have to do is assign a script of somekind to the "web" heading. I named mine `web.sh` in the root of the project. So my procfile looks like this:

    web: ./web.sh

And the contents of the `web.sh` script starts up first the node process, then the rails process.  Here's how mine looks:

```
forevercmd="./node_modules/forever/bin/forever ./app/client/node_server.js"
$forevercmd &disown
bundle exec puma -C config/puma.rb
```

Running forever like that leaves it in the mode where it "logs" to stdout, so that the normal `heroku logs` command shows output from it as well as the rails process. You could use the `forever start` form too, and have it log to a file or whatever, if that is better for your purposes. But it can't block, it has to daemonize or background somehow so that the puma process can start too. And heroku will cut you off after 60 seconds if it takes too long to initialize, so you can't put too much in here (I naively tried putting `npm install` in here in one of my many missteps).

Anyway, hope that helps.

**Comment by ethagnawl** [comment]
Looks like @jeffgran has provided the canonical solution.

@rpunkfu, perhaps it's worth mentioning this solution in the deployment docs? I'd be happy to submit a PR.

**Comment by mattmanske** [comment]
Note for anyone else experiencing issues with this solution. I was able to get it to work, but ran into a few small errors that needed adjustment for my setup:

- Heroku had permission errors on the `web.sh` file initially - had to `chmod` it locally and redeploy.

- The default RWR setup puts the `node_server.js` file under the `react` directory. The first line of the `web.sh` file needed to be changed to 
`forevercmd="./node_modules/forever/bin/forever ./app/react/node_server.js"`

- Heroku threw some unexpected syntax errors when trying to execute the `node_server.js` file. I had to make some adjustments to the default `node_server.js` file generated by RWR. I posted the working file in this gist: https://gist.github.com/mattmanske/4fe7915d949de25556c1ee1f7f6a1744
