### ISSUE TITLE
What are benefits over react_on_rails

### ISSUE THREAD

**Issue by flynfish** [netguru/react_webpack_rails#26]
Hi, I was wondering if there are benefits/key differences between this gem and https://github.com/shakacode/react_on_rails

Thanks!

**Comment by mxaly** [comment]
Hi!
Our goals and focus are a bit different than react_on_rails and this affect implementation & provided features:)
Hopefully v1.0.0 and docs that we are working on will clean this up for you.

For now you can take a look at ongoing implementations of `redux` and `alt.js` integrations. We want them to fully integrate with rails so that developers can have components mounted in various part of rails view and use flux/redux/etc populated with data directly from controllers.
