### ISSUE TITLE
Usage without committing react_bundle.js to git

### ISSUE THREAD

**Issue by axelson** [netguru/react_webpack_rails#37]
Is it possible to use this gem without committing `react_bundle.js` and `react_bundle.css` to git?

**Comment by mxaly** [comment]
Yes:) We have react_bundle.js and react_bundle.css in .gitignore in all projects. This require additional setup on production - need to execute `npm run build` before precompiling assets. We are doing it using capistrano since it's our default but there are different solutions
Take a look here: https://github.com/netguru/react_webpack_rails/blob/master/docs/deployment.md for heroku example and more.

**Comment by axelson** [comment]
But won't that fail locally since `react_bundle.js` and `react_bundle.css` don't exist locally since developers are only running the webpack dev server?

Actually they work just fine in development with an empty file.

**Comment by axelson** [comment]
Would it be okay to suggest that approach in the README? That way developers won't need to run the `webpack` command locally.

**Comment by mxaly** [comment]
You mean creating empty files and adding them to .gitignore? 
I think generator is now creating empty react_bundle.js. So the only problem you can have is when you share project and the empty files won't be there. We can try to figure out a way so that `npm run start-hot-dev` will create them if missing. For now you can use .sample files and add step to bin/setup that will create them.
