### ISSUE TITLE
Using digest image assets

### ISSUE THREAD

**Issue by hajder** [netguru/react_webpack_rails#61]
I'm trying to figure out if there is a way to use this awesome gem together with digested image assets from Rails.

Basically I'd like to keep digesting images to improve caching but be able to somehow include them in my react components.

Any ideas?

**Comment by mxaly** [comment]
Hi @hajder 

Normally i would suggest to use https://github.com/alexspeller/non-stupid-digest-assets and whitelist images that you would like to share with react components. 

Anyway, i was looking for a way to handle digest path somehow. Fastest but ugly solution is to create a rails helper that find asset and return its digest path:
```ruby
  def digest_image(path)
    "assets/#{Rails.application.assets.find_asset(path).digest_path}"
  end
```
and pass images to components by props:
```erb
<%= react_component('myComponent', { data: @data, logoPath: digest_image('logo.svg')}) %>
```

Passing image path each time is not elegant solution so we will consider third option - a plugin which will use generated by sprocets `public/.manifest-xxx.json` file. By using manifest it's possible to create a map of nondigest and digest files and provide helper that will resolve them. Having such helper on js side should solve this problem. 

Let us know what do you think about it.

**Comment by zatapathique** [comment]
Hey @hajder :)

Sorry for late response.

We decided against creating a plugin to our gem to fix this issue since the issue is not directly connected with the gem or React but with how the digested assets work in rails 4. The fact that rails won’t let you compile assets to both digested and non digested version means that your js framework (be it ember, angular, react, backbone etc) will alway have trouble displaying said assets.

**Possible solutions:**

- you can create a map of digested_path => logical_path, pass it to your js and use a helper that resolves logical path to digested path within your components. This is quite ugly.
- you can use https://github.com/alexspeller/non-stupid-digest-assets but this is not really recommended solution since this gem monkey patches sprockets. If the sprockets ever change in a way that breaks the gem it may cause some problems on your servers.
- You can use a rake task that triggers after the assets precompilation. The task fetches the assets map from the sprockets manifest file and copies digested assets to non digested paths. This is actually the solution that we use in our project and so far it is working fine. Granted that it is still dependant on the sprockets manifest file structure but the manifest is less likely to change the the sprockets gem itself. So here is how it looks like in our setup:

task :create_non_digest_assets => :"assets:environment"  do
    logger = Logger.new($stderr)
    excluded_extensions = ['css', 'js']

    manifest_path = Dir[File.join(Rails.root, 'public/assets/.sprockets-manifest-*.json')].first
    manifest_data = JSON.load(File.new(manifest_path))

    manifest_data['files'].each do |digested_path, attributes|
      next if digested_path.ends_with?(*excluded_extensions)

      logical_path = Pathname.new attributes['logical_path']
      full_digested_path = File.join(Rails.root, 'public/assets', digested_path)
      full_nondigested_path = File.join(Rails.root, 'public/assets', logical_path)

      logger.info "Copying asset to #{full_nondigested_path}"

      FileUtils.copy_file full_digested_path, full_nondigested_path, true
    end
  end

We exclude css and js files since we wont really need them within our components. This approach also has the advantage of not having to use any helpers or resolvers within the react components and makes assets work regardless if they are digested or not.

For the further and more in depth read you can checkout this guide -> https://bibwild.wordpress.com/2014/10/02/non-digested-asset-names-in-rails-4-your-options/

Hope it solves your issue :)
