### ISSUE TITLE
Access ReactDOM through RWR?

### ISSUE THREAD

**Issue by gaugau** [netguru/react_webpack_rails#66]
Firstly, I would like to thanks the author and all contributors for such a great gem. It helps us to use both ReactJS and Webpack with existing Rails app.
However, I have a question regarding to this gem. Most of the actions (eg. renderComponent, etc) need to proxy via `RWR`. I'm just wonder if there is a way to access directly to React interface?
Eg. `ReactDOM.render(<HelloMessage name="John" />, mountNode);` 
or `RWR.reactDom` etc

Thanks,

**Comment by mxaly** [comment]
Hi @gaugau 

We created the RWR global so that you don't need to expose stuff from npm packages to use react in js side in your apps .  
However, you can still expose any global you need by assigning it to window/global:
```js
import reactDOM from 'react-dom';
window.ReactDOM = ReactDOM;
```

or when you are using server side:
```js
if (typeof(window) !== 'undefined') {
  window.RWR = this;
} else {
  global.RWR = this;
}
```

Can you maybe describe your case? Why you need ReactDOM globally?

**Comment by gaugau** [comment]
@mxaly We are trying to integrate this gem into our legacy Rails 4 app. I just wonder if later I may need it.
Also, I did not see any example of using CSS module within HelloWorld component? Tried many ways but got no luck. eg. `import css from "./style.css";`

**Comment by gaugau** [comment]
@mxaly  Nevermind, I've figured it out. Thanks for such a great gem!!!
